[config]
schemaVersion = "0.0.1"

[package]
namespace = "Sparroh"
name = "DescriptionOverride"
description = "This is a mod utility to allow me to use the description field within the upgrade asset file."
websiteUrl = "https://github.com/Little-Sparroh/DescriptionOverride"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Mycopunk = "5.4.2403"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "bin/Release/net48/DescriptionOverride.dll"
target = "BepInEx/plugins/DescriptionOverride.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "LICENSE"
target = "LICENSE"

[publish]
repository = "https://thunderstore.io"
communities = [ "mycopunk" ]

[publish.categories]
mycopunk = [ "client" ]


